# build docker image
steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'us-central1-docker.pkg.dev/system-450809/test-cicd-repo/python-image', '.' ]
# push docker image
images:
- 'us-central1-docker.pkg.dev/system-450809/test-cicd-repo/python-image'
options:
 logging: CLOUD_LOGGING_ONLY
